### ISSUE TITLE
Welcome to nginx...

### ISSUE THREAD

**Issue by jrichet** [TenderPro/dockerfile-modperl#3]
After days of mucking with settings and such, this image is finally standing, and all I see is "welcome to nginx"...

Can you please quickly explain the intended usage of this image? 
maybe a demo docker-compose so we know where stuff is supposed to be mounted?

thanks in advance!

**Comment by LeKovr** [comment]
We use this image for running application which needs apache+modperl, nginx and some supervisord services. All we need to run whole project is this image and project source files. Sources are not open so I can not show more details, but can note the following:
1. docker-compose does not contain any image related points, for example volumes part looks like:
```
  volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - /dev/log:/dev/log
      - .:/data
  ```
2. container runs [init.sh](https://github.com/TenderPro/dockerfile-modperl/blob/master/init.d/z-app.sh) at start, so we placed in init.sh some commands for copy config into 
* /usr/local/apache/conf.d/ for apache
* /etc/nginx/conf.d/ for nginx

jrichet, is it enough or may be there are more points to decribe?

**Comment by jrichet** [comment]
that's lots. thank you
